#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

set_java_version() {
  # There are a number of standard ways to change the java version. One is to
  # set JAVA_HOME and PATH, but its possible a build tool could execute
  # /usr/bin/java* directly and use the wrong version. Another option is to use
  # update-alternatives, but that needs slightly different commands for java 8
  # vs java 17, so would make this function more complicated. Instead, we just
  # manually overwrite the java* bin symlinks. This is really only fine because
  # this is always expected to be run in a container.
  JAVA_BIN_ROOT="/usr/lib/jvm/java-$1-openjdk-amd64/bin"
  ln -sf $JAVA_BIN_ROOT/java    /usr/bin/java
  ln -sf $JAVA_BIN_ROOT/javac   /usr/bin/javac
  ln -sf $JAVA_BIN_ROOT/javadoc /usr/bin/javadoc
  ln -sf $JAVA_BIN_ROOT/jar     /usr/bin/jar
}

export WIX=/opt/wix/
export LANG=en_US.UTF-8
export CC=clang
export AR=llvm-ar
export SOURCE_DATE_EPOCH=$(git show --no-patch --format=%ct HEAD)

if [[ "$#" -lt 1 || "$#" -gt 2 ]]
then
    echo "Error: Incorrect number of arguments provided." >&2
    echo "Usage: $0 <project-name> [pre-release-label]" >&2
    exit 1
fi

PROJECT="$1"
if [[ ! $PROJECT =~ ^daffodil(-sbt|-vscode)?$ ]]
then
    echo "Error: Invalid project name. Must be daffodil, daffodil-sbt, or daffodil-vscode, but was $PROJECT" >&2
    exit 1
fi

# determine the release version. If a pre-release label was provided, then append
# it to the project version. Otherwise we just build without a pre-release
# label. This is potentially useful for verifying reproducible builds for final
# releases
PROJECT_VERSION=$(cat VERSION)
if [[ "$#" -eq 2 ]]
then
    PRE_RELEASE_LABEL="$2"
    if [[ ! $PRE_RELEASE_LABEL =~ ^rc[0-9]+$ ]]
    then
        echo "Error: Invalid pre-release label. Must be rcX, but was $PRE_RELEASE_LABEL" >&2
        exit 1
    fi
    RELEASE_VERSION=$PROJECT_VERSION-$PRE_RELEASE_LABEL
else
    RELEASE_VERSION=$PROJECT_VERSION
fi

echo "==== Building artifacts for $PROJECT $RELEASE_VERSION ===="
RELEASE_DIR=/artifacts/release
DIST_DIR=$RELEASE_DIR/asf-dist/$RELEASE_VERSION
MAVEN_DIR=$RELEASE_DIR/maven-local

mkdir -p ~/.sbt/1.0
mkdir -p ~/.sbt/1.0/plugins
echo "ThisBuild / publishTo := Some(MavenCache(\"maven-local\", file(\"$MAVEN_DIR\")))" >> ~/.sbt/1.0/build.sbt
echo "addSbtPlugin(\"com.github.sbt\" %% \"sbt-sbom\" % \"0.4.0\")" >> ~/.sbt/1.0/plugins/plugins.sbt
echo "ThisBuild / bomFormat := \"xml\"" >> ~/.sbt/1.0/build.sbt

echo "==== Building source artifact ===="
mkdir -p $DIST_DIR/src/
git archive --format=zip --prefix=apache-$PROJECT-$PROJECT_VERSION-src/ HEAD > $DIST_DIR/src/apache-$PROJECT-$PROJECT_VERSION-src.zip

echo "==== Building binary artifacts ===="

case $PROJECT in
  "daffodil")
    set_java_version 17
    mkdir -p $DIST_DIR/bin
    sbt \
      +compile \
      +publish \
      daffodil-cli/Rpm/packageBin \
      daffodil-cli/packageWindowsBin \
      daffodil-cli/Universal/packageBin \
      daffodil-cli/Universal/packageZipTarball

    cp daffodil-cli/target/universal/apache-daffodil-*.tgz $DIST_DIR/bin/
    cp daffodil-cli/target/universal/apache-daffodil-*.zip $DIST_DIR/bin/
    cp daffodil-cli/target/rpm/RPMS/noarch/apache-daffodil-*.rpm $DIST_DIR/bin/
    cp daffodil-cli/target/windows/apache-daffodil-*.exe $DIST_DIR/bin/
    chmod -x $DIST_DIR/bin/*.exe
    ;;

  "daffodil-sbt")
    set_java_version 17
    sbt \
      "^compile" \
      "^publish"
    ;;

  "daffodil-vscode")
    set_java_version 17
    mkdir -p $DIST_DIR/bin/
    yarn package
    cp *.vsix $DIST_DIR/bin/
    ;;

esac

echo "==== Calculating Checksums ===="

for i in $DIST_DIR/*/
do
    pushd $i > /dev/null
    for file in *
    do
       sha512sum --binary $file > $file.sha512
    done
    popd &> /dev/null
done
